-- return  {
--   {
--   -- "morhetz/gruvbox",
--   "rafamadriz/gruvbox",
--   lazy = false,
--   name = "gruvbox",
--   init = function()
--     vim.g.gruvbox_contrast_dark = "hard"
--   end,
--   opts = {
--     contrast = "hard",
--   },
-- }
-- }
